@Thoth.API_HostAddress = http://localhost:5142

GET {{Thoth.API_HostAddress}}/api/organizations

POST {{Thoth.API_HostAddress}}/api/organizations
Content-Type: application/json

{
  "name": "My Organization"
}

PUT {{Thoth.API_HostAddress}}/api/organizations
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Organization Name"
}

DELETE {{Thoth.API_HostAddress}}/api/organizations/1
