@Thoth.API_HostAddress = http://localhost:5142
###
GET {{Thoth.API_HostAddress}}/api/roles
Content-Type: application/json

###
POST {{Thoth.API_HostAddress}}/api/roles
Content-Type: application/json

{
  "name": "Admin",
  "permissionIds": [4, 5]
}

###
PUT {{Thoth.API_HostAddress}}/api/roles
Content-Type: application/json

{
  "id": 3,
  "name": "SuperAdmin2",
  "permissionIds": [2, 5]
}

###
DELETE {{Thoth.API_HostAddress}}/api/roles/4
Content-Type: application/json


