@Thoth.API_HostAddress = http://localhost:5142

POST {{Thoth.API_HostAddress}}/api/organizations
Content-Type: application/json

{
  "name": "My Organization"
}

### (error)
POST {{Thoth.API_HostAddress}}/api/organizations
Content-Type: application/json

{
  "name": ""
}
